version: "3"
services:
  app:
    container_name: currency-converter
    restart: always
    build: ./
    ports:
      - "8000:8000"
    environment:
      - PORT=8000
    volumes:
      - .:/app
      - /usr/src/app/node_modules
